### PR TITLE
[WIP] FIX #113: NoSuchMethodError currentBinaryVersion For ScalaJs 1.0.0

### LINKED ISSUE #113: NoSuchMethodError currentBinaryVersion For ScalaJs 1.0.0
The Converter SBT plugin does work for scala version 1.0.0

https://github.com/ScalablyTyped/Converter/blob/master/sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala#L100

is using a method that what removed on commit:

https://github.com/scala-js/scala-js/commit/61e7bfa25eb4296d5ac3ec1e5bd1889479be1e63

This is causing https://github.com/ScalablyTyped/Demos/issues/21

### PR DESCRIPTION
**Pull request by FabioPinheiro**
This is just [WIP] because I'm waiting for the new version of scalajs-bundler to be published.
Since https://github.com/scalacenter/scalajs-bundler/pull/324#event-3044771159 is already merged.

With the new version of scalajs-bundler, we use the solution from @gzm0 (https://github.com/ScalablyTyped/Demos/issues/21#issuecomment-587046901) for the ScalaJs versions 0.6 and 1.0 without having to support each version independently.

I published everything local and tested with the ScalablyTyped/Demos and it seems to work with ScalaJs 1.0.0

### CODE REVIEW

**Comment by oyvindberg** [comment]
Thanks @FabioPinheiro ! I'll merge this as soon as we have a new version of scalajs-bundler :)

**Comment by oyvindberg** [comment]
By the way @FabioPinheiro I wanted to try this now. I havent compiled a custom version of scalajs-bundler yet, and without it I got
a compile error:
```
[error] .../sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterExternalNpmPlugin.scala:64:43: object ir is not a member of package org.scalajs
[error]           scalaJsBinVersion = org.scalajs.ir.ScalaJSVersions.binaryCross,
```

Can you compile it for both versions of the plugin on your side? If there's no way having source compatibility between 0.6 and 1.0 I'm pretty tempted to just write an ad hoc function which figures it out from the version number

**Comment by FabioPinheiro** [comment]
I'm almost sure I test the Demo with both versions of ScalaJs and that worked after compiling scalajs-bundler with:
`SCALAJS_VERSION=1.0.0 sbt -no-colors ";^^1.2.8;publishLocal"`
`SCALAJS_VERSION=0.6.31 sbt -no-colors ";^^1.2.8;publishLocal"`

Feel free to get head and fix this other way. Don't know if's worth the wait.
Maybe we can ask @julienrf when will the new version of the plugin be published.

**Comment by oyvindberg** [comment]
OK cool! :) We'll need a new release of scalajs-bundler in any case, I tripped into another bug that seems to be fixed on master when trying the workaround with adding the scalajs linker to `plugins.sbt`.

The good news is that with a local build and a slinky prerelease build, I made all the slinky demos work, see https://github.com/ScalablyTyped/SlinkyDemos/pull/10

**Comment by julienrf** [comment]
scalajs-bundler 0.17.0 has been published

**Comment by oyvindberg** [comment]
I'll just merge this and bump it to release version. Thanks again @FabioPinheiro
